fork_me_ribbon_url: https://github.com/wikfeldt/git-collaborative
baseurl: "/git-collaborative"
title: "Collaborative distributed version control"
centralized_workflow_exercise_url: https://github.com/KTH-dESA/centralized-workflow-exercise
forking_workflow_exercise_url: https://github.com/KTH-dESA/forking-workflow-exercise

source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']

collections:
  episodes:
    output: true
    permalink: /:name/
  # guides are in a collection, otherwise site variables
  # like centralized_workflow_exercise_url are not understood
  guides:
    output: true
    permalink: /:name/
